core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: null # http://apm_server:8200/
    elasticsearch:
      hosts: [http://elastic:devpass@elasticsearch:9200]
    redis:
      host: redis
  redis:
    nonpersistent:
      host: redis
    persistent:
      host: redis
      port: 6379

datastore:
  hosts: [http://elastic:devpass@elasticsearch:9200]

filestore:
  cache:
    [
      "s3://al_storage_key:Ch@ngeTh!sPa33w0rd@minio:9000?s3_bucket=al-cache&use_ssl=False",
    ]
  storage:
    [
      "s3://al_storage_key:Ch@ngeTh!sPa33w0rd@minio:9000?s3_bucket=al-storage&use_ssl=False",
    ]
  # cache:
  #   - file:///home/kamil/Devel/lab-analysing-pkgs/assemblyline/var/cache/assemblyline

logging:
  export_interval: 30
  log_to_console: true
  log_to_file: false
  log_to_syslog: false

services:
  preferred_update_channel: dev
  allow_insecure_registry: true
  image_variables:
    PRIVATE_REGISTRY: $PRIVATE_REGISTRY

ui:
  enforce_quota: false
