name: test-detecting-version-changes
run-name: Detecting changes in VERSION files
on:
  push:
    branches:
      - main
    paths:
      - '*/VERSION'
jobs:
  print-changed-services:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Store services with changed VERSION files
        id: changed-services
        run: |
          echo "::set-output name=services::$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | grep '/VERSION$' | cut -d '/' -f 1 | uniq)"
      - name: Print services with changed VERSION files
        run: |
          echo "Services with changed VERSION files: ${{ steps.changed-services.outputs.services }}"